// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./src/layout/AppLayout.vue')['default']
    AsideDir: typeof import('./src/layout/AsideDir.vue')['default']
    AsideFile: typeof import('./src/layout/AsideFile.vue')['default']
    AsideFolder: typeof import('./src/layout/AsideFolder.vue')['default']
    AsideNote: typeof import('./src/layout/AsideNote.vue')['default']
    AsideResize: typeof import('./src/components/AsideResize.vue')['default']
    CodiconChromeClose: typeof import('~icons/codicon/chrome-close')['default']
    CodiconChromeMaximize: typeof import('~icons/codicon/chrome-maximize')['default']
    CodiconChromeMinimize: typeof import('~icons/codicon/chrome-minimize')['default']
    CodiconChromeRestore: typeof import('~icons/codicon/chrome-restore')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTree: typeof import('element-plus/es')['ElTree']
    EpAddLocation: typeof import('~icons/ep/add-location')['default']
    EpAim: typeof import('~icons/ep/aim')['default']
    EpDelete: typeof import('~icons/ep/delete')['default']
    EpEdit: typeof import('~icons/ep/edit')['default']
    EpFold: typeof import('~icons/ep/fold')['default']
    EpSetting: typeof import('~icons/ep/setting')['default']
    EpShare: typeof import('~icons/ep/share')['default']
    IconParkOutlinePreviewOpen: typeof import('~icons/icon-park-outline/preview-open')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    MainEdit: typeof import('./src/layout/MainEdit.vue')['default']
    MdiPlusThick: typeof import('~icons/mdi/plus-thick')['default']
    PajamasListBulleted: typeof import('~icons/pajamas/list-bulleted')['default']
    PajamasListNumbered: typeof import('~icons/pajamas/list-numbered')['default']
    PajamasTodoDone: typeof import('~icons/pajamas/todo-done')['default']
    TheEditor: typeof import('./src/components/TheEditor.vue')['default']
    TreePane: typeof import('./src/components/TreePane.vue')['default']
  }
}
